### ISSUE TITLE
free(): invalid pointer error

### ISSUE THREAD

**Issue by NikiBe** [vice87/gam-ngs#10]
Hi,

When running gam-create I get the error below. I have also copied the output of 'gdb backtrace' at the bottom of this issue. Does anyone have an idea how to solve this problem? It is a pretty large dataset (genome of ~3 Gbp) so memory limitations may play a role. However, the systems' memory use (>500 Gb RAM) was not at its limit (only ~20% was in use when the error occurred).

Thanks for your help!

**\* glibc detected **\* /gam-ngs/bin/gam-create: free(): invalid pointer: 0x00000000006ffce0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x33af276126]
/usr/lib64/libstdc++.so.6(_ZNSs6assignERKSs+0x85)[0x33b929d565]
/gam-ngs/bin/gam-create(_ZN8BamTools12BamAlignmentaSERKS0_+0x23)[0x462325]
/gam-ngs/bin/gam-create(_ZN14MultiBamReader16GetNextAlignmentERN8BamTools12BamAlignmentEb+0x105)[0x4744e3]
/gam-ngs/bin/gam-create(_ZN5Block10findBlocksERSt6vectorIS_SaIS_EER14MultiBamReaderiRN6google15sparse_hash_mapISs4ReadNSt3tr14hashISsEESt8equal_toISsENS6_27libc_allocator_with_reallocISt4pairIKSsS8_EEEEESK_RS0_IS0_IjSaIjEESaISM_EE+0x9c8)[0x46cc78]
/gam-ngs/bin/gam-create(_ZN7modules12CreateBlocks7executeEv+0x61d)[0x452585]
/gam-ngs/bin/gam-create(main+0x4e)[0x4510e2]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x33af21ecdd]
/gam-ngs/bin/gam-create[0x450fd9]
======= Memory map: ========
00400000-004d8000 r-xp 00000000 08:11 35652018                           /gam-ngs/bin/gam-create
006d8000-006da000 rw-p 000d8000 08:11 35652018                           /gam-ngs/bin/gam-create
006da000-24861f9000 rw-p 00000000 00:00 0                                [heap]
33aea00000-33aea20000 r-xp 00000000 fd:00 1451235                        /lib64/ld-2.12.so
...
....
Program received signal SIGABRT, Aborted.
0x00000033af2328e5 in raise () from /lib64/libc.so.6
###### 

Running gdb backtrace resulted in the following:

(gdb) backtrace
#0  0x00000033af2328e5 in raise () from /lib64/libc.so.6
#1  0x00000033af2340c5 in abort () from /lib64/libc.so.6
#2  0x00000033af2707f7 in __libc_message () from /lib64/libc.so.6
#3  0x00000033af276126 in malloc_printerr () from /lib64/libc.so.6
#4  0x00000033b929d565 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib64/libstdc++.so.6
#5  0x0000000000462325 in BamTools::BamAlignment::operator= (this=0x7fffffffd8b0) at /gam-ngs/lib/bamtools-2.0.5/src/api/BamAlignment.h:32
#6  0x00000000004744e3 in MultiBamReader::GetNextAlignment (this=0x7fffffffdc00, align=..., update_stats=true) at /gam-ngs/lib/src/bam/MultiBamReader.cc:323
#7  0x000000000046cc78 in Block::findBlocks (outblocks=std::vector of length 3574546, capacity 4194304 = {...}, bamReader=..., minBlockSize=10, readsMap_1=..., readsMap_2=...,

```
coverage=std::vector of length 177072, capacity 177072 = {...}) at /gam-ngs/lib/src/assembly/Block.cc:495
```
#8  0x0000000000452585 in modules::CreateBlocks::execute (this=0x7fffffffe1b0) at /gam-ngs/src/CreateBlocks.cc:141
#9  0x00000000004510e2 in main (argc=9, argv=0x7fffffffe2c8) at /gam-ngs/src/gam-create.cc:49

**Comment by vice87** [comment]
I'm sorry for replying so late. I've updated the source code with a recent version of the library used to handle BAMs. Hopefully, this fixed the problem.
